[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { features = ["full"], version = "1.0" }

[features]
default = []
framework = []

[lib]
proc-macro = true

[package]
authors = ["Zondax GmbH <info@zondax.ch>"]
name = "zondee-macros"
version = "0.1.0"
edition = "2018"
readme = "README.md"
