name: Build sample
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # So we can trigger manually
  workflow_dispatch:

env:
  QEMU_V8: 1
  SHARED_FOLDER: ${HOME}/qemu-shared-folder/
  OPTEE: ${HOME}/actions-runner/optee-qemuv8-3.12.0
  SCRIPTS: ${HOME}/actions-runner/scripts

jobs:
  prepare:
    runs-on: tee-ci

    steps:
      - run: mkdir -p $SHARED_FOLDER
      - run: cp -r $SCRIPTS $SHARED_FOLDER/scripts

  build:
    needs: prepare

    # Run this workflow in our optee self-hosted runner
    runs-on: tee-ci

    steps:
      # Check out the framework locally
      - uses: actions/checkout@v2

      # Check out the tee-template echo application
      - uses: actions/checkout@v2
        with:
          repository: "Zondax/tee-substrate-service"
          ref: "tee-template"
          path: "tee-template"
          token: ${{ secrets.TEE_TEMPLATE_TOKEN }}
          submodules: "true"

      - name: Build the application
        run: SRC=tee-template make

  test:
    needs: [prepare, build]
    runs-on: tee-ci

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "Zondax/tee-substrate-service"
          ref: "tee-template"
          path: "tee-template"
          token: ${{ secrets.TEE_TEMPLATE_TOKEN }}
          submodules: "true"

      - name: Run the application tests
        run: SRC=tee-template make ci run
